/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutIdRouteRouteImport } from './routes/$workoutId/route'
import { Route as TabsRouteRouteImport } from './routes/_tabs/route'
import { Route as ActiveRouteRouteImport } from './routes/active/route'
import { Route as WorkoutIdIndexRouteImport } from './routes/$workoutId/index'
import { Route as WorkoutIdExercisesRouteImport } from './routes/$workoutId/exercises'
import { Route as TabsIndexRouteImport } from './routes/_tabs/index'
import { Route as TabsHistoryRouteImport } from './routes/_tabs/history'
import { Route as TabsSettingsRouteImport } from './routes/_tabs/settings'
import { Route as WorkoutIdHistoryIndexRouteImport } from './routes/$workoutId/history/index'
import { Route as WorkoutIdHistoryHistoryIdRouteImport } from './routes/$workoutId/history/$historyId'
import { Route as ActiveHistoryIdIndexRouteImport } from './routes/active/$historyId/index'
import { Route as ActiveHistoryIdExerciseIdRouteImport } from './routes/active/$historyId/$exerciseId'

const WorkoutIdRouteRoute = WorkoutIdRouteRouteImport.update({
  id: '/$workoutId',
  path: '/$workoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRouteRoute = TabsRouteRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveRouteRoute = ActiveRouteRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIdIndexRoute = WorkoutIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkoutIdRouteRoute,
} as any)
const WorkoutIdExercisesRoute = WorkoutIdExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => WorkoutIdRouteRoute,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRouteRoute,
} as any)
const TabsHistoryRoute = TabsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => TabsRouteRoute,
} as any)
const TabsSettingsRoute = TabsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TabsRouteRoute,
} as any)
const WorkoutIdHistoryIndexRoute = WorkoutIdHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => WorkoutIdRouteRoute,
} as any)
const WorkoutIdHistoryHistoryIdRoute =
  WorkoutIdHistoryHistoryIdRouteImport.update({
    id: '/history/$historyId',
    path: '/history/$historyId',
    getParentRoute: () => WorkoutIdRouteRoute,
  } as any)
const ActiveHistoryIdIndexRoute = ActiveHistoryIdIndexRouteImport.update({
  id: '/$historyId/',
  path: '/$historyId/',
  getParentRoute: () => ActiveRouteRoute,
} as any)
const ActiveHistoryIdExerciseIdRoute =
  ActiveHistoryIdExerciseIdRouteImport.update({
    id: '/$historyId/$exerciseId',
    path: '/$historyId/$exerciseId',
    getParentRoute: () => ActiveRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$workoutId': typeof WorkoutIdRouteRouteWithChildren
  '/': typeof TabsIndexRoute
  '/active': typeof ActiveRouteRouteWithChildren
  '/$workoutId/exercises': typeof WorkoutIdExercisesRoute
  '/history': typeof TabsHistoryRoute
  '/settings': typeof TabsSettingsRoute
  '/$workoutId/': typeof WorkoutIdIndexRoute
  '/$workoutId/history/$historyId': typeof WorkoutIdHistoryHistoryIdRoute
  '/active/$historyId/$exerciseId': typeof ActiveHistoryIdExerciseIdRoute
  '/$workoutId/history/': typeof WorkoutIdHistoryIndexRoute
  '/active/$historyId/': typeof ActiveHistoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/active': typeof ActiveRouteRouteWithChildren
  '/$workoutId/exercises': typeof WorkoutIdExercisesRoute
  '/history': typeof TabsHistoryRoute
  '/settings': typeof TabsSettingsRoute
  '/$workoutId': typeof WorkoutIdIndexRoute
  '/': typeof TabsIndexRoute
  '/$workoutId/history/$historyId': typeof WorkoutIdHistoryHistoryIdRoute
  '/active/$historyId/$exerciseId': typeof ActiveHistoryIdExerciseIdRoute
  '/$workoutId/history': typeof WorkoutIdHistoryIndexRoute
  '/active/$historyId': typeof ActiveHistoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$workoutId': typeof WorkoutIdRouteRouteWithChildren
  '/_tabs': typeof TabsRouteRouteWithChildren
  '/active': typeof ActiveRouteRouteWithChildren
  '/$workoutId/exercises': typeof WorkoutIdExercisesRoute
  '/_tabs/history': typeof TabsHistoryRoute
  '/_tabs/settings': typeof TabsSettingsRoute
  '/$workoutId/': typeof WorkoutIdIndexRoute
  '/_tabs/': typeof TabsIndexRoute
  '/$workoutId/history/$historyId': typeof WorkoutIdHistoryHistoryIdRoute
  '/active/$historyId/$exerciseId': typeof ActiveHistoryIdExerciseIdRoute
  '/$workoutId/history/': typeof WorkoutIdHistoryIndexRoute
  '/active/$historyId/': typeof ActiveHistoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$workoutId'
    | '/'
    | '/active'
    | '/$workoutId/exercises'
    | '/history'
    | '/settings'
    | '/$workoutId/'
    | '/$workoutId/history/$historyId'
    | '/active/$historyId/$exerciseId'
    | '/$workoutId/history/'
    | '/active/$historyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/active'
    | '/$workoutId/exercises'
    | '/history'
    | '/settings'
    | '/$workoutId'
    | '/'
    | '/$workoutId/history/$historyId'
    | '/active/$historyId/$exerciseId'
    | '/$workoutId/history'
    | '/active/$historyId'
  id:
    | '__root__'
    | '/$workoutId'
    | '/_tabs'
    | '/active'
    | '/$workoutId/exercises'
    | '/_tabs/history'
    | '/_tabs/settings'
    | '/$workoutId/'
    | '/_tabs/'
    | '/$workoutId/history/$historyId'
    | '/active/$historyId/$exerciseId'
    | '/$workoutId/history/'
    | '/active/$historyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkoutIdRouteRoute: typeof WorkoutIdRouteRouteWithChildren
  TabsRouteRoute: typeof TabsRouteRouteWithChildren
  ActiveRouteRoute: typeof ActiveRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$workoutId': {
      id: '/$workoutId'
      path: '/$workoutId'
      fullPath: '/$workoutId'
      preLoaderRoute: typeof WorkoutIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active': {
      id: '/active'
      path: '/active'
      fullPath: '/active'
      preLoaderRoute: typeof ActiveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workoutId/': {
      id: '/$workoutId/'
      path: '/'
      fullPath: '/$workoutId/'
      preLoaderRoute: typeof WorkoutIdIndexRouteImport
      parentRoute: typeof WorkoutIdRouteRoute
    }
    '/$workoutId/exercises': {
      id: '/$workoutId/exercises'
      path: '/exercises'
      fullPath: '/$workoutId/exercises'
      preLoaderRoute: typeof WorkoutIdExercisesRouteImport
      parentRoute: typeof WorkoutIdRouteRoute
    }
    '/_tabs/': {
      id: '/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof TabsRouteRoute
    }
    '/_tabs/history': {
      id: '/_tabs/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof TabsHistoryRouteImport
      parentRoute: typeof TabsRouteRoute
    }
    '/_tabs/settings': {
      id: '/_tabs/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof TabsSettingsRouteImport
      parentRoute: typeof TabsRouteRoute
    }
    '/$workoutId/history/': {
      id: '/$workoutId/history/'
      path: '/history'
      fullPath: '/$workoutId/history/'
      preLoaderRoute: typeof WorkoutIdHistoryIndexRouteImport
      parentRoute: typeof WorkoutIdRouteRoute
    }
    '/$workoutId/history/$historyId': {
      id: '/$workoutId/history/$historyId'
      path: '/history/$historyId'
      fullPath: '/$workoutId/history/$historyId'
      preLoaderRoute: typeof WorkoutIdHistoryHistoryIdRouteImport
      parentRoute: typeof WorkoutIdRouteRoute
    }
    '/active/$historyId/': {
      id: '/active/$historyId/'
      path: '/$historyId'
      fullPath: '/active/$historyId/'
      preLoaderRoute: typeof ActiveHistoryIdIndexRouteImport
      parentRoute: typeof ActiveRouteRoute
    }
    '/active/$historyId/$exerciseId': {
      id: '/active/$historyId/$exerciseId'
      path: '/$historyId/$exerciseId'
      fullPath: '/active/$historyId/$exerciseId'
      preLoaderRoute: typeof ActiveHistoryIdExerciseIdRouteImport
      parentRoute: typeof ActiveRouteRoute
    }
  }
}

interface WorkoutIdRouteRouteChildren {
  WorkoutIdExercisesRoute: typeof WorkoutIdExercisesRoute
  WorkoutIdIndexRoute: typeof WorkoutIdIndexRoute
  WorkoutIdHistoryHistoryIdRoute: typeof WorkoutIdHistoryHistoryIdRoute
  WorkoutIdHistoryIndexRoute: typeof WorkoutIdHistoryIndexRoute
}

const WorkoutIdRouteRouteChildren: WorkoutIdRouteRouteChildren = {
  WorkoutIdExercisesRoute: WorkoutIdExercisesRoute,
  WorkoutIdIndexRoute: WorkoutIdIndexRoute,
  WorkoutIdHistoryHistoryIdRoute: WorkoutIdHistoryHistoryIdRoute,
  WorkoutIdHistoryIndexRoute: WorkoutIdHistoryIndexRoute,
}

const WorkoutIdRouteRouteWithChildren = WorkoutIdRouteRoute._addFileChildren(
  WorkoutIdRouteRouteChildren,
)

interface TabsRouteRouteChildren {
  TabsHistoryRoute: typeof TabsHistoryRoute
  TabsSettingsRoute: typeof TabsSettingsRoute
  TabsIndexRoute: typeof TabsIndexRoute
}

const TabsRouteRouteChildren: TabsRouteRouteChildren = {
  TabsHistoryRoute: TabsHistoryRoute,
  TabsSettingsRoute: TabsSettingsRoute,
  TabsIndexRoute: TabsIndexRoute,
}

const TabsRouteRouteWithChildren = TabsRouteRoute._addFileChildren(
  TabsRouteRouteChildren,
)

interface ActiveRouteRouteChildren {
  ActiveHistoryIdExerciseIdRoute: typeof ActiveHistoryIdExerciseIdRoute
  ActiveHistoryIdIndexRoute: typeof ActiveHistoryIdIndexRoute
}

const ActiveRouteRouteChildren: ActiveRouteRouteChildren = {
  ActiveHistoryIdExerciseIdRoute: ActiveHistoryIdExerciseIdRoute,
  ActiveHistoryIdIndexRoute: ActiveHistoryIdIndexRoute,
}

const ActiveRouteRouteWithChildren = ActiveRouteRoute._addFileChildren(
  ActiveRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkoutIdRouteRoute: WorkoutIdRouteRouteWithChildren,
  TabsRouteRoute: TabsRouteRouteWithChildren,
  ActiveRouteRoute: ActiveRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
