/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutIdRouteRouteImport } from './routes/$workoutId/route'
import { Route as ActiveRouteRouteImport } from './routes/active/route'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as WorkoutIdIndexRouteImport } from './routes/$workoutId/index'
import { Route as WorkoutIdExercisesRouteImport } from './routes/$workoutId/exercises'
import { Route as WorkoutIdReorderRouteImport } from './routes/$workoutId/reorder'
import { Route as WorkoutIdHistoryIndexRouteImport } from './routes/$workoutId/history/index'
import { Route as WorkoutIdHistoryHistoryIdRouteImport } from './routes/$workoutId/history/$historyId'
import { Route as ActiveHistoryIdIndexRouteImport } from './routes/active/$historyId/index'
import { Route as ActiveHistoryIdExerciseIdRouteImport } from './routes/active/$historyId/$exerciseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIdRouteRoute = WorkoutIdRouteRouteImport.update({
  id: '/$workoutId',
  path: '/$workoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveRouteRoute = ActiveRouteRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIdIndexRoute = WorkoutIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkoutIdRouteRoute,
} as any)
const WorkoutIdExercisesRoute = WorkoutIdExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => WorkoutIdRouteRoute,
} as any)
const WorkoutIdReorderRoute = WorkoutIdReorderRouteImport.update({
  id: '/reorder',
  path: '/reorder',
  getParentRoute: () => WorkoutIdRouteRoute,
} as any)
const WorkoutIdHistoryIndexRoute = WorkoutIdHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => WorkoutIdRouteRoute,
} as any)
const WorkoutIdHistoryHistoryIdRoute =
  WorkoutIdHistoryHistoryIdRouteImport.update({
    id: '/history/$historyId',
    path: '/history/$historyId',
    getParentRoute: () => WorkoutIdRouteRoute,
  } as any)
const ActiveHistoryIdIndexRoute = ActiveHistoryIdIndexRouteImport.update({
  id: '/$historyId/',
  path: '/$historyId/',
  getParentRoute: () => ActiveRouteRoute,
} as any)
const ActiveHistoryIdExerciseIdRoute =
  ActiveHistoryIdExerciseIdRouteImport.update({
    id: '/$historyId/$exerciseId',
    path: '/$historyId/$exerciseId',
    getParentRoute: () => ActiveRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$workoutId': typeof WorkoutIdRouteRouteWithChildren
  '/active': typeof ActiveRouteRouteWithChildren
  '/history': typeof HistoryRoute
  '/$workoutId/exercises': typeof WorkoutIdExercisesRoute
  '/$workoutId/reorder': typeof WorkoutIdReorderRoute
  '/$workoutId/': typeof WorkoutIdIndexRoute
  '/$workoutId/history/$historyId': typeof WorkoutIdHistoryHistoryIdRoute
  '/active/$historyId/$exerciseId': typeof ActiveHistoryIdExerciseIdRoute
  '/$workoutId/history/': typeof WorkoutIdHistoryIndexRoute
  '/active/$historyId/': typeof ActiveHistoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/active': typeof ActiveRouteRouteWithChildren
  '/history': typeof HistoryRoute
  '/$workoutId/exercises': typeof WorkoutIdExercisesRoute
  '/$workoutId/reorder': typeof WorkoutIdReorderRoute
  '/$workoutId': typeof WorkoutIdIndexRoute
  '/$workoutId/history/$historyId': typeof WorkoutIdHistoryHistoryIdRoute
  '/active/$historyId/$exerciseId': typeof ActiveHistoryIdExerciseIdRoute
  '/$workoutId/history': typeof WorkoutIdHistoryIndexRoute
  '/active/$historyId': typeof ActiveHistoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$workoutId': typeof WorkoutIdRouteRouteWithChildren
  '/active': typeof ActiveRouteRouteWithChildren
  '/history': typeof HistoryRoute
  '/$workoutId/exercises': typeof WorkoutIdExercisesRoute
  '/$workoutId/reorder': typeof WorkoutIdReorderRoute
  '/$workoutId/': typeof WorkoutIdIndexRoute
  '/$workoutId/history/$historyId': typeof WorkoutIdHistoryHistoryIdRoute
  '/active/$historyId/$exerciseId': typeof ActiveHistoryIdExerciseIdRoute
  '/$workoutId/history/': typeof WorkoutIdHistoryIndexRoute
  '/active/$historyId/': typeof ActiveHistoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workoutId'
    | '/active'
    | '/history'
    | '/$workoutId/exercises'
    | '/$workoutId/reorder'
    | '/$workoutId/'
    | '/$workoutId/history/$historyId'
    | '/active/$historyId/$exerciseId'
    | '/$workoutId/history/'
    | '/active/$historyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/active'
    | '/history'
    | '/$workoutId/exercises'
    | '/$workoutId/reorder'
    | '/$workoutId'
    | '/$workoutId/history/$historyId'
    | '/active/$historyId/$exerciseId'
    | '/$workoutId/history'
    | '/active/$historyId'
  id:
    | '__root__'
    | '/'
    | '/$workoutId'
    | '/active'
    | '/history'
    | '/$workoutId/exercises'
    | '/$workoutId/reorder'
    | '/$workoutId/'
    | '/$workoutId/history/$historyId'
    | '/active/$historyId/$exerciseId'
    | '/$workoutId/history/'
    | '/active/$historyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkoutIdRouteRoute: typeof WorkoutIdRouteRouteWithChildren
  ActiveRouteRoute: typeof ActiveRouteRouteWithChildren
  HistoryRoute: typeof HistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workoutId': {
      id: '/$workoutId'
      path: '/$workoutId'
      fullPath: '/$workoutId'
      preLoaderRoute: typeof WorkoutIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active': {
      id: '/active'
      path: '/active'
      fullPath: '/active'
      preLoaderRoute: typeof ActiveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workoutId/': {
      id: '/$workoutId/'
      path: '/'
      fullPath: '/$workoutId/'
      preLoaderRoute: typeof WorkoutIdIndexRouteImport
      parentRoute: typeof WorkoutIdRouteRoute
    }
    '/$workoutId/exercises': {
      id: '/$workoutId/exercises'
      path: '/exercises'
      fullPath: '/$workoutId/exercises'
      preLoaderRoute: typeof WorkoutIdExercisesRouteImport
      parentRoute: typeof WorkoutIdRouteRoute
    }
    '/$workoutId/reorder': {
      id: '/$workoutId/reorder'
      path: '/reorder'
      fullPath: '/$workoutId/reorder'
      preLoaderRoute: typeof WorkoutIdReorderRouteImport
      parentRoute: typeof WorkoutIdRouteRoute
    }
    '/$workoutId/history/': {
      id: '/$workoutId/history/'
      path: '/history'
      fullPath: '/$workoutId/history/'
      preLoaderRoute: typeof WorkoutIdHistoryIndexRouteImport
      parentRoute: typeof WorkoutIdRouteRoute
    }
    '/$workoutId/history/$historyId': {
      id: '/$workoutId/history/$historyId'
      path: '/history/$historyId'
      fullPath: '/$workoutId/history/$historyId'
      preLoaderRoute: typeof WorkoutIdHistoryHistoryIdRouteImport
      parentRoute: typeof WorkoutIdRouteRoute
    }
    '/active/$historyId/': {
      id: '/active/$historyId/'
      path: '/$historyId'
      fullPath: '/active/$historyId/'
      preLoaderRoute: typeof ActiveHistoryIdIndexRouteImport
      parentRoute: typeof ActiveRouteRoute
    }
    '/active/$historyId/$exerciseId': {
      id: '/active/$historyId/$exerciseId'
      path: '/$historyId/$exerciseId'
      fullPath: '/active/$historyId/$exerciseId'
      preLoaderRoute: typeof ActiveHistoryIdExerciseIdRouteImport
      parentRoute: typeof ActiveRouteRoute
    }
  }
}

interface WorkoutIdRouteRouteChildren {
  WorkoutIdExercisesRoute: typeof WorkoutIdExercisesRoute
  WorkoutIdReorderRoute: typeof WorkoutIdReorderRoute
  WorkoutIdIndexRoute: typeof WorkoutIdIndexRoute
  WorkoutIdHistoryHistoryIdRoute: typeof WorkoutIdHistoryHistoryIdRoute
  WorkoutIdHistoryIndexRoute: typeof WorkoutIdHistoryIndexRoute
}

const WorkoutIdRouteRouteChildren: WorkoutIdRouteRouteChildren = {
  WorkoutIdExercisesRoute: WorkoutIdExercisesRoute,
  WorkoutIdReorderRoute: WorkoutIdReorderRoute,
  WorkoutIdIndexRoute: WorkoutIdIndexRoute,
  WorkoutIdHistoryHistoryIdRoute: WorkoutIdHistoryHistoryIdRoute,
  WorkoutIdHistoryIndexRoute: WorkoutIdHistoryIndexRoute,
}

const WorkoutIdRouteRouteWithChildren = WorkoutIdRouteRoute._addFileChildren(
  WorkoutIdRouteRouteChildren,
)

interface ActiveRouteRouteChildren {
  ActiveHistoryIdExerciseIdRoute: typeof ActiveHistoryIdExerciseIdRoute
  ActiveHistoryIdIndexRoute: typeof ActiveHistoryIdIndexRoute
}

const ActiveRouteRouteChildren: ActiveRouteRouteChildren = {
  ActiveHistoryIdExerciseIdRoute: ActiveHistoryIdExerciseIdRoute,
  ActiveHistoryIdIndexRoute: ActiveHistoryIdIndexRoute,
}

const ActiveRouteRouteWithChildren = ActiveRouteRoute._addFileChildren(
  ActiveRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkoutIdRouteRoute: WorkoutIdRouteRouteWithChildren,
  ActiveRouteRoute: ActiveRouteRouteWithChildren,
  HistoryRoute: HistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
